export const products= [
    {
      name: 'Montre pasha de cartier',
      slug: 'Montre-pasha-de-cartier',
      category: 'Montres',
      images: ['1.webp','2.webp','3.webp'],
      price: "129.000",
      brand: 'cartier',
      countInStock: 20,
      description: 'Mouvement mécanique à remontage automatique 1847 MC',
    },
    {
        name: 'Montre ballon bleu de cartier',
        slug: 'Montre-ballon-bleu-de-cartier',
        category: 'Montres',
        images: ['4.webp'],
        price: "86.000",
        brand: 'cartier',
        countInStock: 20,
        description: 'Mouvement mécanique à remontage automatique 1847 MC',
      },
      {
        name: 'Montre pasha de cartier',
        slug: 'Montre-pasha-de-cartier',
        category: 'Montres',
        images: ['1.webp','2.webp','3.webp'],
        price: "129.000",
        brand: 'cartier',
        countInStock: 20,
        description: 'Mouvement mécanique à remontage automatique 1847 MC',
      },
      {
        name: 'Montre pasha de cartier',
        slug: 'Montre-pasha-de-cartier',
        category: 'Montres',
        images: ['1.webp','2.webp','3.webp'],
        price: "129.000",
        brand: 'cartier',
        countInStock: 20,
        description: 'Mouvement mécanique à remontage automatique 1847 MC',
      },
      {
        name: 'Montre pasha de cartier',
        slug: 'Montre-pasha-de-cartier',
        category: 'Montres',
        images: ['1.webp','2.webp','3.webp'],
        price: "129.000",
        brand: 'cartier',
        countInStock: 20,
        description: 'Mouvement mécanique à remontage automatique 1847 MC',
      },
  ]